{% set name = "epix-uhr-dev" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-{{ version }}.tar.gz
  sha256: 300459b7227e65e06e8ab725fc16756944ac125cf6301f0597c7b53b56618760 
  patches:
    - setup.patch

build:
  skip: True  # [win or osx]
  noarch: python
  number: 5
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

about:
  home: https://github.com/slaclab/epix-uhr-dev
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Epix UHR software and firmware'
  description: |
    firmware for Epix UHR devices.
  doc_url: https://github.com/slaclab/epix-uhr-dev
  dev_url: https://github.com/slaclab/epix-uhr-dev

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
    - melchior
